import Head from "next/head";
import { useEffect, useRef } from "react";
import Avatar from "../components/Avatar";
import Image from "next/image";
import { ViewGridIcon, MicrophoneIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
import Footer from "../components/Footer";
import { useRouter } from "next/router";

export default function Home() {
  const inputRef = useRef();
  const router = useRouter();

  const handleSearch = (e) => {
    e.preventDefault();
    const searchQuery = inputRef.current.value;
    // Guard clause
    if (!searchQuery || searchQuery.trim().length === 0) return;
    router.push(`/search?q=${searchQuery}`);
  };

  useEffect(() => {
    inputRef.current.focus();
  }, []);

  return (
    <div className="min-h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="flex justify-end items-center p-6 text-sm text-gray-700">
        {/* Left */}

        {/* Right */}
        <div className="flex space-x-4 items-center">
          {/* Icon */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />

          {/* Avatar */}
          <Avatar url="https://i.imgur.com/Ls9edAT.jpg" />
        </div>
      </header>
      {/* Body */}
      <form
        className="flex flex-col items-center mt-44 flex-grow"
        onSubmit={handleSearch}
      >
        <Image
          src="https://www.google.se/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
          alt="Picture of the author"
          width={272}
          height={92}
          quality={100}
        />
        <div
          className="flex w-full mt-5 hover:shadow focus-within:shadow max-w-md py-3 px-5 rounded-full items-center border border-gray-200 sm:max-w-xl lg:max-w-2xl"
          onClick={() => {
            inputRef.current.focus();
          }}
        >
          <SearchIcon className="h-5 w-5 mr-3 text-gray-500" />
          <input
            ref={inputRef}
            type="text"
            className="flex-grow text-base outline-none"
          />
          <MicrophoneIcon className="h-5 w-5 ml-3 text-gray-500" />
        </div>

        <div className="flex space-x-4 mt-5">
          <button className="button" type="submit">
            Google Search
          </button>
          <button className="button" type="submit">
            I'm Feeling Lucky
          </button>
        </div>
      </form>
      {/* Footer */}
      <Footer />
    </div>
  );
}
